### ISSUE TITLE
Freeze certain layers

### ISSUE THREAD

**Issue by JasAva** [JDAI-CV/fast-reid#178]
Thanks for the amazing implementation.
For a recent update on freezing certain layers, I noticed that instead of setting param.require_grad as False, current code give param_group['freeze'] = True. However, I can't find the code that specifically set require_grad based on the ['freeze']. I print out some of the backbone params, though param_group['freeze'] = True, the requires_grad is still True, essentially the certain layers are not frozen.
Can you shed some insights on this? Thanks.

**Comment by L1aoXingyu** [comment]
You can see this line below

https://github.com/JDAI-CV/fast-reid/blob/ee634df2900996233473cb95a80029bd456cce97/fastreid/solver/optim/adam.py#L68

We change from `param.requres_grad` to `param_group['freeze']` because in DDP training, it will raise an error when changing the `requires_grad` of param during training.

**Comment by JasAva** [comment]
Thank you, close this issue now.
