### ISSUE TITLE
Some questions on Video ReID

### ISSUE THREAD

**Issue by shen338** [JDAI-CV/fast-reid#218]
First of all, thank you for this amazing work! Well-formed and super easy to use! 

1. what inputs you will provide, if any:
    A video ReID dataset, several sequences of video clips. All the identities are annotated with a unique id. 

2. what outputs you are expecting: 
    Given one person's image that appears in a video, find this person **only in this video**. 

With this kind of video ReID task, I have several problems: 

1. I plan to directly build backbones like resnet and load the weight directly from .pth file. The reason is, this sample code demo/predictor.py contains a lot of dependencies, which makes it harder for me to integrate. In this way, I have to make the image preprocessing identical to training. In preprocessing, fastreid accepts BGR images, and subtract pixel_mean and divide pixel_std. 

```
# Values to be used for image normalization
_C.MODEL.PIXEL_MEAN = [0.485*255, 0.456*255, 0.406*255]
# Values to be used for image normalization
_C.MODEL.PIXEL_STD = [0.229*255, 0.224*255, 0.225*255]
```

Seems like this pixel_mean and pixel_std is in RGB order? 

And in my understanding, the preprocessing only contains subtract pixel_mean and divide pixel_std. Is this correct?

2. Another question is about the common practice to sample a video ReID dataset. Right now I have a 30 FPS video dataset, do I need to use every person in every sequence to generate the dataset? Or sparse sampling is better? I am afraid this might bring too many easy instances, since person in consecutive frames tends to be very similar.  
Will fastreid support Video ReID in the future? The [Deep person reid](https://github.com/KaiyangZhou/deep-person-reid) has this feature, but still based on image ReID. 

3. The last question is about PK sampling. My video looks very different to each other and the identities from different sequences might be overlapped. So, I am considering sample negatives identities only from the same video clip rather than sampling from the whole dataset. Do yo have any thoughts on this? Could you give me a pointer to the code I need to change? 

Any answer will be appreciated. Thank you!

**Comment by L1aoXingyu** [comment]
1. The best practice for building a model is to export to ONNX or TensorRT, then you can remove all the dependencies. The only thing you need to do is writing the preprocessing.
The preprocessing is just resize, because subtract mean and divide std have been moved into the network as follow

https://github.com/JDAI-CV/fast-reid/blob/9c667d1a0fbd8a6b5a82ad4d04d51b47d6b2957a/fastreid/modeling/meta_arch/baseline.py#L74

You can check the preprocess here

https://github.com/JDAI-CV/fast-reid/blob/9c667d1a0fbd8a6b5a82ad4d04d51b47d6b2957a/demo/predictor.py#L51

BTW, the image is `RGB` order.

2. You can just pick 2 or 3 images from each video clip because they are very similar. We won't consider Video ReID in the future because you can process the video clip offline and then use fastreid for training.

3. The better way is to do the data clean, for example, merge the same ids in the overlapped video clips.
