### ISSUE TITLE
May be a bug about AutoAugment

### ISSUE THREAD

**Issue by culeao** [JDAI-CV/fast-reid#219]
![image](https://user-images.githubusercontent.com/35450998/89604704-61796700-d89e-11ea-8720-e2595d46826f.png)

![image](https://user-images.githubusercontent.com/35450998/89604172-44906400-d89d-11ea-8158-7b5f98189e58.png)

when we set max_iter = 60(num_epochs), that means it do nothing after the __call__() function is called 60 times.
That is, after the first epoch processes 60 images, AutoAugment does not work. 

This is obviously unreasonable.
Maybe my understanding is wrong, I look forward to solving my doubts.

Thank you!

**Comment by L1aoXingyu** [comment]
Yes! This is a bug and I am fixing it.

**Comment by culeao** [comment]
![image](https://user-images.githubusercontent.com/35450998/89732513-fa1c0c80-da81-11ea-81bf-5ef58ca4f51e.png)

I think

**Comment by L1aoXingyu** [comment]
Actually `autoaugment` refers to here

https://github.com/layumi/AICIty-reID-2020/blob/3f329884e1ad6d770bbda6d89bf894aa6b14c4eb/pytorch/train_2020.py#L286

In this code, it just did autoaugmnet for the whole batch data and decided to choose the original transforms or autoaugment transforms by a certain probability.

I found it's difficult to add in my fastreid, so I just applied the autoaugment transform for just one image rather than a whole batch. 

Just like you said, the number of training images should be passed in, but I did some experiments these days and found it will drop the performance so I just modified it to the number of iters.

You can do some experiments and discuss with me here.
