### ISSUE TITLE
Got 0 class (ids) when run evaluate

### ISSUE THREAD

**Issue by AnhPC03** [JDAI-CV/fast-reid#281]
I had trained fastreid with my own dataset then archived my checkpoint.
My dataset has 280 ids in training set also query set and galerry set.
Camid in gallery set is different from query set.
When i had trained, it logged 280 ids, but when i evaluated by command:
```
python tools/train_net.py --config-file ./configs/Market1501/sbs_R50.yml --eval-only \
MODEL.WEIGHTS /path/to/checkpoint_file MODEL.DEVICE "cuda:0"
```
It warned:
```
'heads.classifier.weight' has shape (280, 2048) in the checkpoint but (0, 2048) in the model! Skipped.
Some model parameters are not in the checkpoint: heads.classifier.weight
```
but in below of that warning was:
```
| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| query    | 280     | 22416      | 1           |
| gallery  | 280     | 7812       | 1           |
```
It showed that 280 ids.
I don't understand why had above warning, and how it affected my evaluation result?

**Comment by hsfzxjy** [comment]
It won't affect the evaluation, since only features before classifier are used during evaluation.

**Comment by AnhPC03** [comment]
@hsfzxjy So, how can i know how good my model could make true re-id in my query set?

**Comment by addisonklinke** [comment]
In `engine.defaults.py:DefaultTrainer.auto_scale_hyperparams()`, the auto-scaling sets `cfg.MODEL.HEADS.NUM_CLASSES` to match `data_loader.dataset.num_classes`. 

I think the `config.yaml` files that get saved to the log folder should reflect this change (whereas now they still show zero). This way, when you build a model from a config (for evaluation or export), it will have the appropriate classifier size to match the pre-trained weights. Otherwise, you would need to hard-code the config value or build the data loader to dynamically determine the value (which is a waste of compute)

**Comment by L1aoXingyu** [comment]
@addisonklinke Thanks for your suggestions, I will think about it.
