### ISSUE TITLE
How to train ResNet-50 on person and vehicle ReID datasets like MSMT17 and VeRi? 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [JDAI-CV/fast-reid#329]
## ❓ How to do something using fastreid

Hi, I want to train ResNet-50 for person and vehicle on MSMT17 and VeRi dataset. 

1- Can I train ResNet for two classes and use both datasets at the same time or I need to train one by one? 
2- What is the training process? 
2- Can I also use ResNet-18 or ResNet-34  in the same way to increase the speed? 

My ultimate goal is to train ResNet ReID model for the person and car. and then combine with this project (https://github.com/GeekAlexis/FastMOT) for Fast multi-object tracking. 

How I can achieve this goal?

**Comment by L1aoXingyu** [comment]
Actually, I did not try to combine person and vehicle into one reid model. Because the input size of person reid is 128x256 and vehicle reid is 256x256.

My suggestion is that training two reid models, one for person reid and the other for vehicle reid. The upstream task is detection, so you can use detection results to decide which reid model needs.
