### ISSUE TITLE
模型load

### ISSUE THREAD

**Issue by decajcd** [JDAI-CV/fast-reid#486]
我想问下model zoo里提供的权重都是最新的吗？与模型是否匹配
我load了SBS(R101-ibn)模型，会出现下面的问题：
[05/12 07:50:43 fastreid.utils.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
  heads.bottleneck.0.{bias, weight, running_var, running_mean}
[05/12 07:50:43 fastreid.utils.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
  heads.bnneck.{weight, bias, running_mean, running_var, num_batches_tracked}
请问如何解决

**Comment by L1aoXingyu** [comment]
model zoo 里面的模型有一些参数已经对不上了，要不你重新 train 一个，要不你就 `torch.load` model zoo 里面的参数，其实是一个字典，然后你改一下对应的 key

**Comment by deep-practice** [comment]
重新训练模型之后，为什么还是有些参数加载不了呢，同一个config
[06/11 13:23:57 fastreid.data.datasets.bases]: => Loaded DukeMTMC in csv format: 
| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| query    | 702     | 2228       | 8           |
| gallery  | 1110    | 17661      | 8           |
[06/11 13:24:01 fastreid.utils.checkpoint]: Loading checkpoint from logs/dukemtmc/mgn_R50-ibn/model_best.pth
WARNING [06/11 13:24:02 fastreid.utils.checkpoint]: Skip loading parameter 'b1_head.weight' to the model due to incompatible shapes: (702, 256) in the checkpoint but (0, 256) in the model! You might want to double check if this is expected.
WARNING [06/11 13:24:02 fastreid.utils.checkpoint]: Skip loading parameter 'b2_head.weight' to the model due to incompatible shapes: (702, 256) in the checkpoint but (0, 256) in the model! You might want to double check if this is expected.
WARNING [06/11 13:24:02 fastreid.utils.checkpoint]: Skip loading parameter 'b21_head.weight' to the model due to incompatible shapes: (702, 256) in the checkpoint but (0, 256) in the model! You might want to double check if this is expected.
WARNING [06/11 13:24:02 fastreid.utils.checkpoint]: Skip loading parameter 'b22_head.weight' to the model due to incompatible shapes: (702, 256) in the checkpoint but (0, 256) in the model! You might want to double check if this is expected.
WARNING [06/11 13:24:02 fastreid.utils.checkpoint]: Skip loading parameter 'b3_head.weight' to the model due to incompatible shapes: (702, 256) in the checkpoint but (0, 256) in the model! You might want to double check if this is expected.
WARNING [06/11 13:24:02 fastreid.utils.checkpoint]: Skip loading parameter 'b31_head.weight' to the model due to incompatible shapes: (702, 256) in the checkpoint but (0, 256) in the model! You might want to double check if this is expected.
WARNING [06/11 13:24:02 fastreid.utils.checkpoint]: Skip loading parameter 'b32_head.weight' to the model due to incompatible shapes: (702, 256) in the checkpoint but (0, 256) in the model! You might want to double check if this is expected.
WARNING [06/11 13:24:02 fastreid.utils.checkpoint]: Skip loading parameter 'b33_head.weight' to the model due to incompatible shapes: (702, 256) in the checkpoint but (0, 256) in the model! You might want to double check if this is expected.
[06/11 13:24:02 fastreid.utils.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
  b2_head.weight
  b21_head.weight
  b3_head.weight
  b32_head.weight
  b22_head.weight
  b1_head.weight
  b31_head.weight
  b33_head.weight

**Comment by L1aoXingyu** [comment]
这是分类器的 weight，不 load 进去也不影响 reid 测试结果，如果需要 load 进去，使用你保存模型下面的 config.yaml，不过你现在估计应该覆盖了那个 config，你可以直接修改 config 里面的类别数量，就可以成功 load 进去

**Comment by deep-practice** [comment]
明白了。
