### ISSUE TITLE
how can i use your code and weights to combine similar objects

### ISSUE THREAD

**Issue by daliel** [JDAI-CV/fast-reid#499]
I read this
**`3. We do not answer general machine learning / computer vision questions that are not specific to fastreid, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.`**

but maybe someone will tell you in general outline how it is possible to implement this.
input data:
    the largest crop of each tracker on one camera.
since I know that the sort algorithm is not working perfectly, and I need to weed out duplicate objects. I decided to use re-identification after processing the video.
I used pretrained weights for the veriwild. slightly changed merged the code demo/demo.py and demo/visualize_result.py.
```
# encoding: utf-8
"""
@author:  liaoxingyu
@contact: sherlockliao01@gmail.com
"""

import argparse
import logging
import glob
import os
import sys

import cv2
import numpy as np
import tqdm
import torch
import tqdm
from torch.backends import cudnn

sys.path.append('.')

from fastreid.config import get_cfg
from fastreid.evaluation import evaluate_rank
from fastreid.utils.logger import setup_logger
from fastreid.utils.file_io import PathManager
from fastreid.utils.visualizer import Visualizer
from fastreid.data.transforms import build_transforms
from fastreid.data.common import CommDataset
from fastreid.data.build import build_reid_test_loader

from predictor import FeatureExtractionDemo

# import some modules added in project like this below
# sys.path.append('../projects/PartialReID')
# from partialreid import *

cudnn.benchmark = True
setup_logger(name="fastreid")

logger = logging.getLogger('fastreid.visualize_result')

def setup_cfg(args):
    # load config from file and command-line arguments
    cfg = get_cfg()
    # add_partialreid_config(cfg)
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.freeze()
    return cfg


def get_parser():
    parser = argparse.ArgumentParser(description="Feature extraction with reid models")
    parser.add_argument(
        "--config-file",
        metavar="FILE",
        help="path to config file",
    )
    parser.add_argument(
        "--parallel",
        action='store_true',
        help='If use multiprocess for feature extraction.'
    )
    parser.add_argument(
        "--input",
        nargs="+",
        help="A list of space separated input images; "
             "or a single glob pattern such as 'directory/*.jpg'",
    )
    parser.add_argument(
        "--output",
        default='demo_output',
        help='path to save features'
    )
    parser.add_argument(
        "--vis-label",
        action='store_true',
        help="if visualize label of query instance"
    )
    parser.add_argument(
        "--num-vis",
        default=100,
        help="number of query images to be visualized",
    )
    parser.add_argument(
        "--rank-sort",
        default="ascending",
        help="rank order of visualization images by AP metric",
    )
    parser.add_argument(
        "--label-sort",
        default="ascending",
        help="label order of visualization images by cosine similarity metric",
    )
    parser.add_argument(
        "--max-rank",
        default=10,
        help="maximum number of rank list to be visualized",
    )
    parser.add_argument(
        "--opts",
        help="Modify config options using the command-line 'KEY VALUE' pairs",
        default=[],
        nargs=argparse.REMAINDER,
    )
    return parser


if __name__ == '__main__':
    args = get_parser().parse_args()
    cfg = setup_cfg(args)
    #print(cfg["TEST"]["IMS_PER_BATCH"])
    demo = FeatureExtractionDemo(cfg, parallel=args.parallel)

    PathManager.mkdirs(args.output)
    if args.input:
        if PathManager.isdir(args.input[0]):
            args.input = glob.glob(os.path.expanduser(args.input[0]))
            assert args.input, "The input path(s) was not found"
        feats = []
        pids = []
        camids = []
        dataset_q = []
        dataset_g = []
        for path in tqdm.tqdm(args.input):
            img = cv2.imread(path)
            feat = demo.run_on_image(img)
            feats.append(feat)
            pids.append(os.path.basename(path)[:-4])
            camids.append(0)
            dataset_q.append((path, os.path.basename(path)[:-4], 0))
            dataset_q.append((path, os.path.basename(path)[:-4], 1))
        dataset = dataset_q+dataset_g
        feats = torch.cat(feats, dim=0)
        q_feat = feats
        g_feat = feats
        q_pids = np.asarray(pids)
        g_pids = np.asarray(pids)
        q_camids = np.asarray(camids)
        g_camids = np.asarray(camids)+1
        transforms = build_transforms(cfg, is_train=False)
        test_set = CommDataset(dataset, transforms, relabel=False)
        test_loader, num_query = build_reid_test_loader(test_set, 1, len(q_pids))
        # compute cosine distance
        distmat = 1 - torch.mm(q_feat, g_feat.t())
        distmat = distmat.numpy()
        
        logger.info("Computing APs for all query images ...")
        cmc, all_ap, all_inp = evaluate_rank(distmat, q_pids, g_pids, q_camids, g_camids, use_cython=False)
        logger.info("Finish computing APs for all query images!")

        visualizer = Visualizer(test_loader.dataset)
        visualizer.get_model_output(all_ap, distmat, q_pids, g_pids, q_camids, g_camids)

        logger.info("Start saving ROC curve ...")
        fpr, tpr, pos, neg = visualizer.vis_roc_curve(args.output)
        visualizer.save_roc_info(args.output, fpr, tpr, pos, neg)
        logger.info("Finish saving ROC curve!")

        logger.info("Saving rank list result ...")
        query_indices = visualizer.vis_rank_list(args.output, args.vis_label, args.num_vis,
                                                 args.rank_sort, args.label_sort, args.max_rank)
        logger.info("Finish saving rank list results!")
```
and here is the result:
![6](https://user-images.githubusercontent.com/6017469/119987469-be7d0f80-bfcd-11eb-8595-b7a4552930d5.jpg)

its output to console:
```
python3 demo/demo_visualize.py --config-file /media/daliel/hdd/fast-reid/logs/veriwild/bagtricks_R50-ibn_4gpu/config.yaml --input /media/daliel/hdd/from_main/deepstream/deepstream-test1_2/crops_0_0/*.jpg --output /media/daliel/hdd/tmp/ --opts MODEL.WEIGHTS /media/daliel/hdd/fast-reid/datasets/VERI-Wild/veriwild_bot_R50-ibn.pth
[05/28 14:19:31 fastreid.utils.checkpoint]: Loading checkpoint from /media/daliel/hdd/fast-reid/datasets/VERI-Wild/veriwild_bot_R50-ibn.pth
[05/28 14:19:32 fastreid.utils.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
  heads.weight
  heads.bnneck.{weight, bias, running_var, running_mean}
[05/28 14:19:32 fastreid.utils.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
  heads.bottleneck.0.{weight, bias, running_mean, running_var, num_batches_tracked}
  heads.classifier.weight
100%|██████████████████████████████████████████████████████████████████| 573/573 [00:18<00:00, 30.42it/s]
[05/28 14:19:51 fastreid.visualize_result]: Computing APs for all query images ...
[05/28 14:19:52 fastreid.visualize_result]: Finish computing APs for all query images!
[05/28 14:19:52 fastreid.visualize_result]: Start saving ROC curve ...
[05/28 14:19:53 fastreid.visualize_result]: Finish saving ROC curve!
[05/28 14:19:53 fastreid.visualize_result]: Saving rank list result ...
100%|██████████████████████████████████████████████████████████████████| 100/100 [01:09<00:00,  1.43it/s]
[05/28 14:21:03 fastreid.visualize_result]: Finish saving rank list results!
```

**what am I doing wrong?**

**Comment by L1aoXingyu** [comment]
![image](https://user-images.githubusercontent.com/19245504/120981174-f9d7c500-c7a9-11eb-89bc-a82f3507dbcb.png)

Notice here, parameters are not fully loaded. This is due to the version of fastreid changing.
You can use this [version of fastreid](https://github.com/JDAI-CV/fast-reid/tree/v0.1.1) or modify the key in `verwild_bot_R50-ibn.pth` or just train a new model by yourself.

**Comment by fciverchia** [comment]
Hi, 
I have executed the code snippet provided by daliel with the following configurations and pretrained weights:
- configs/VeRi/sbs_R50-ibn.yml, veri_sbs_R50-ibn.pth
- configs/VERIWild/bagtricks_R50-ibn.yml, veriwild_bot_R50-ibn.pth

The images test folder contains the same image repeated 150 times. 

I got the following results:

![0](https://user-images.githubusercontent.com/35819253/122781466-21ea1c80-d2b0-11eb-82e5-3068caf3a5df.jpg)

It seems the intelligence is not able to correctly detect. Why do I obtain such a result?

This is the console output:

> python demo/demo_visualize.py --config-file configs/VeRi/sbs_R50-ibn.yml --input samecar_test/*.jpg --output /tmp/ --parallel --opts MODEL.WEIGHTS veri_sbs_R50-ibn.pth 
  0%|                                                                                                                                                                                      | 0/150 [00:00<?, ?it/s][06/21 14:54:56 fastreid.utils.checkpoint]: Loading checkpoint from veri_sbs_R50-ibn.pth
[06/21 14:54:57 fastreid.utils.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
  heads.weight
[06/21 14:54:57 fastreid.utils.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
  heads.bnneck.num_batches_tracked
  heads.classifier.weight
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:16<00:00,  9.18it/s]
/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py:258: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
[06/21 14:55:07 fastreid.visualize_result]: Computing APs for all query images ...
[06/21 14:55:07 fastreid.visualize_result]: Finish computing APs for all query images!
[06/21 14:55:07 fastreid.visualize_result]: Start saving ROC curve ...
[06/21 14:55:08 fastreid.visualize_result]: Finish saving ROC curve!
[06/21 14:55:08 fastreid.visualize_result]: Saving rank list result ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:51<00:00,  1.12s/it]
[06/21 14:56:59 fastreid.visualize_result]: Finish saving rank list results!
[W CudaIPCTypes.cpp:21] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

Do you have any suggestions? What am I doing wrong?

Thank you

**Comment by L1aoXingyu** [comment]
Maybe @daliel can help you. He modifies this code.
