### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by rafaelbate** [JDAI-CV/fast-reid#527]
[FIX]

When trying to convert fastreid model to trt  using trt_export.py, I got the following error:

```
Traceback (most recent call last):
  File "/content/fast-reid/tools/deploy/trt_export.py", line 13, in <module>
    from trt_calibrator import FeatEntropyCalibrator
  File "/content/fast-reid/tools/deploy/trt_calibrator.py", line 29, in <module>
    from fastreid.data.build import _root
ModuleNotFoundError: No module named 'fastreid'
```

To fix this, I edited the file "trt_calibrator.py" in line24:

`sys.path.append('../..')`

to

`sys.path.append('.')`

Then I got another error:

`AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'build_cuda_engine'`

Which I fixed using:

`pip install nvidia-tensorrt==7.2.* --index-url https://pypi.ngc.nvidia.com`

This fixed the issue for me, hope someone finds this useful.

**Comment by berylyellow** [comment]
@rafaelbate Hi~ I met the same problem as you. I followed your steps, and converted tensorrt engine successfully. But when I do trt_inference, another problem occurs：

[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin InstanceNormalization_TRT version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (322) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "trt_inference.py", line 187, in <module>
    trt = TrtEngine(args.model_path, batch_size=args.batch_size)
  File "trt_inference.py", line 80, in __init__
    self._context = self._engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
Exception ignored in: <function TrtEngine.__del__ at 0x7f6cad888290>
Traceback (most recent call last):
  File "trt_inference.py", line 177, in __del__
    del self._input
AttributeError: _input
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
Aborted (core dumped)

Did you meet this problem? And whats your running environment？

Wait for your reply~
